//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// File generated on 9/3/2019 4:40:52 PM
namespace WaveEngine.Sponza
{
    using System;
    
    
    public sealed class WaveContent
    {
        
        public sealed class Scenes
        {
            
            /// <summary> Asset Path (Scenes/MyScene.wescene.wesc) </summary>
            public static readonly Guid MyScene_wescene = new Guid("0bc26ca0-7cea-479d-81bd-ade510541882");
        }
        
        public sealed class Effects
        {
            
            /// <summary> Asset Path (Effects/StandardEffect.wefx) </summary>
            public static readonly Guid StandardEffect = new Guid("dab1f60a-82ad-40fc-8fbb-7b85caa6de0a");
        }
        
        public sealed class Textures
        {
            
            /// <summary> Asset Path (Textures/Checker.png.wetx) </summary>
            public static readonly Guid Checker_png = new Guid("8b1d459c-c433-4ee3-bfe5-b45fbce12736");
        }
        
        public sealed class Samplers
        {
            
            /// <summary> Asset Path (Samplers/LinearClampSampler.wesp) </summary>
            public static readonly Guid LinearClampSampler = new Guid("7d1e2792-2031-42bb-a67c-0dbd282be12a");
            
            /// <summary> Asset Path (Samplers/LinearWrapSampler.wesp) </summary>
            public static readonly Guid LinearWrapSampler = new Guid("9018edf8-ea96-4721-bf83-5561942432e0");
        }
        
        public sealed class Materials
        {
            
            /// <summary> Asset Path (Materials/DefaultMaterial.wemt) </summary>
            public static readonly Guid DefaultMaterial = new Guid("02181b63-5a0e-46d1-9208-d92376ae33fb");
        }
        
        public sealed class Sponza
        {
            
            /// <summary> Asset Path (Sponza/Sponza.bin.wefile) </summary>
            public static readonly Guid Sponza_bin = new Guid("4d8ef701-cfad-43fa-bebc-b9c3035dca65");
            
            /// <summary> Asset Path (Sponza/8006627369776289000.png.wetx) </summary>
            public static readonly Guid _8006627369776289000_png = new Guid("4147cc9b-eae6-440c-9473-8b5fa6345090");
            
            /// <summary> Asset Path (Sponza/5823059166183034438.jpg.wetx) </summary>
            public static readonly Guid _5823059166183034438_jpg = new Guid("4770cc87-a37d-42ba-991e-6c091d0981f8");
            
            /// <summary> Asset Path (Sponza/715093869573992647.jpg.wetx) </summary>
            public static readonly Guid _715093869573992647_jpg = new Guid("fda1b3e9-b346-4114-81e3-33e81a67291a");
            
            /// <summary> Asset Path (Sponza/14118779221266351425.jpg.wetx) </summary>
            public static readonly Guid _14118779221266351425_jpg = new Guid("142a00cf-4956-4cda-b51c-6921706ff84e");
            
            /// <summary> Asset Path (Sponza/8114461559286000061.jpg.wetx) </summary>
            public static readonly Guid _8114461559286000061_jpg = new Guid("f06051ac-2ec9-4ed3-aea1-07978dbf1053");
            
            /// <summary> Asset Path (Sponza/5792855332885324923.jpg.wetx) </summary>
            public static readonly Guid _5792855332885324923_jpg = new Guid("6c4df214-86a5-4b1c-a2c1-f1862e64d5df");
            
            /// <summary> Asset Path (Sponza/1219024358953944284.jpg.wetx) </summary>
            public static readonly Guid _1219024358953944284_jpg = new Guid("bbff5e99-d143-42ff-8aa4-5d7688e861da");
            
            /// <summary> Asset Path (Sponza/8773302468495022225.jpg.wetx) </summary>
            public static readonly Guid _8773302468495022225_jpg = new Guid("314215af-f7e6-4bca-8ae5-a4d0ed12e8b1");
            
            /// <summary> Asset Path (Sponza/11474523244911310074.jpg.wetx) </summary>
            public static readonly Guid _11474523244911310074_jpg = new Guid("62e9ae86-49f0-4292-b0df-dab6b23e41e5");
            
            /// <summary> Asset Path (Sponza/3628158980083700836.jpg.wetx) </summary>
            public static readonly Guid _3628158980083700836_jpg = new Guid("ae6a8ad0-737d-4706-8a0f-b0e93ed1c23d");
            
            /// <summary> Asset Path (Sponza/6047387724914829168.jpg.wetx) </summary>
            public static readonly Guid _6047387724914829168_jpg = new Guid("532debe2-ad99-4a03-bb24-e0b3ae796a82");
            
            /// <summary> Asset Path (Sponza/9288698199695299068.jpg.wetx) </summary>
            public static readonly Guid _9288698199695299068_jpg = new Guid("4b01fc28-ef3a-43dd-bc0d-528d05145bc7");
            
            /// <summary> Asset Path (Sponza/6667038893015345571.jpg.wetx) </summary>
            public static readonly Guid _6667038893015345571_jpg = new Guid("02c44764-e094-4661-b802-aebe03b1f2de");
            
            /// <summary> Asset Path (Sponza/2969916736137545357.jpg.wetx) </summary>
            public static readonly Guid _2969916736137545357_jpg = new Guid("a0c45f47-e6e6-4bab-86dc-0c9d4298dce2");
            
            /// <summary> Asset Path (Sponza/11872827283454512094.jpg.wetx) </summary>
            public static readonly Guid _11872827283454512094_jpg = new Guid("dabdcf49-00dd-4b6c-95da-037266e62398");
            
            /// <summary> Asset Path (Sponza/759203620573749278.jpg.wetx) </summary>
            public static readonly Guid _759203620573749278_jpg = new Guid("0f3638da-5b7a-41f4-9019-05c897630b1f");
            
            /// <summary> Asset Path (Sponza/Sponza.gltf.wemd) </summary>
            public static readonly Guid Sponza_gltf = new Guid("ab8cc918-cc5d-4d4c-8b20-660a05a12faa");
            
            /// <summary> Asset Path (Sponza/11968150294050148237.jpg.wetx) </summary>
            public static readonly Guid _11968150294050148237_jpg = new Guid("ece20f9f-372b-41c2-a609-edcb1f0b861d");
            
            /// <summary> Asset Path (Sponza/5061699253647017043.png.wetx) </summary>
            public static readonly Guid _5061699253647017043_png = new Guid("fd0f0408-37a3-42c9-8185-f9644d41c524");
            
            /// <summary> Asset Path (Sponza/16275776544635328252.png.wetx) </summary>
            public static readonly Guid _16275776544635328252_png = new Guid("963b7804-08b5-45b1-92e7-0115384d09be");
            
            /// <summary> Asset Path (Sponza/4975155472559461469.jpg.wetx) </summary>
            public static readonly Guid _4975155472559461469_jpg = new Guid("b6da797c-a3aa-40b9-86d4-2934622ae53d");
            
            /// <summary> Asset Path (Sponza/4910669866631290573.jpg.wetx) </summary>
            public static readonly Guid _4910669866631290573_jpg = new Guid("63714747-f11b-44f2-8e1f-018ebef4adbb");
            
            /// <summary> Asset Path (Sponza/3371964815757888145.jpg.wetx) </summary>
            public static readonly Guid _3371964815757888145_jpg = new Guid("ab782fba-4a14-4832-91a4-a862622781f7");
            
            /// <summary> Asset Path (Sponza/17556969131407844942.jpg.wetx) </summary>
            public static readonly Guid _17556969131407844942_jpg = new Guid("39605871-2949-4bd6-bb61-63cc23a1cb62");
            
            /// <summary> Asset Path (Sponza/2411100444841994089.jpg.wetx) </summary>
            public static readonly Guid _2411100444841994089_jpg = new Guid("fcfd9968-5ae5-4481-b421-e36c3f234f30");
            
            /// <summary> Asset Path (Sponza/10381718147657362067.jpg.wetx) </summary>
            public static readonly Guid _10381718147657362067_jpg = new Guid("248293d1-c8ab-4c2a-a7cd-be2bf5f2415f");
            
            /// <summary> Asset Path (Sponza/15722799267630235092.jpg.wetx) </summary>
            public static readonly Guid _15722799267630235092_jpg = new Guid("fd8603a0-2219-423e-92b1-2b60986542a6");
            
            /// <summary> Asset Path (Sponza/7268504077753552595.jpg.wetx) </summary>
            public static readonly Guid _7268504077753552595_jpg = new Guid("64cc10c8-afaa-4ed7-817c-44b2fb1ffed7");
            
            /// <summary> Asset Path (Sponza/3827035219084910048.jpg.wetx) </summary>
            public static readonly Guid _3827035219084910048_jpg = new Guid("f201d47d-bc3c-45ad-93d1-f2cc28815cde");
            
            /// <summary> Asset Path (Sponza/9916269861720640319.jpg.wetx) </summary>
            public static readonly Guid _9916269861720640319_jpg = new Guid("164ebd07-fb1d-4a79-950c-142cb0c45272");
            
            /// <summary> Asset Path (Sponza/16885566240357350108.jpg.wetx) </summary>
            public static readonly Guid _16885566240357350108_jpg = new Guid("ef2ddedd-0212-4ad5-9784-de5334d71566");
            
            /// <summary> Asset Path (Sponza/6593109234861095314.jpg.wetx) </summary>
            public static readonly Guid _6593109234861095314_jpg = new Guid("3e4fb541-7a97-4ba7-bcbe-ce3d9483ae95");
            
            /// <summary> Asset Path (Sponza/13982482287905699490.jpg.wetx) </summary>
            public static readonly Guid _13982482287905699490_jpg = new Guid("a37a3f0b-b815-4146-a0c4-75feddfbdc52");
            
            /// <summary> Asset Path (Sponza/2775690330959970771.jpg.wetx) </summary>
            public static readonly Guid _2775690330959970771_jpg = new Guid("6afac27c-02fc-4262-8eb3-366d772dde97");
            
            /// <summary> Asset Path (Sponza/8481240838833932244.jpg.wetx) </summary>
            public static readonly Guid _8481240838833932244_jpg = new Guid("cfafa936-e4cf-475b-89f9-bd012641e592");
            
            /// <summary> Asset Path (Sponza/8783994986360286082.jpg.wetx) </summary>
            public static readonly Guid _8783994986360286082_jpg = new Guid("cb7ef89a-ea6d-4b42-b3b9-2334bb9a4d07");
            
            /// <summary> Asset Path (Sponza/14267839433702832875.jpg.wetx) </summary>
            public static readonly Guid _14267839433702832875_jpg = new Guid("03d14ad1-a8f4-43c4-86e3-3d7744dd5f14");
            
            /// <summary> Asset Path (Sponza/2299742237651021498.jpg.wetx) </summary>
            public static readonly Guid _2299742237651021498_jpg = new Guid("ee68e3d0-9c32-4f59-a06a-205e8f116d86");
            
            /// <summary> Asset Path (Sponza/4871783166746854860.jpg.wetx) </summary>
            public static readonly Guid _4871783166746854860_jpg = new Guid("7a13cc94-9424-4f0f-8c67-3f833610db34");
            
            /// <summary> Asset Path (Sponza/8750083169368950601.jpg.wetx) </summary>
            public static readonly Guid _8750083169368950601_jpg = new Guid("79f148e9-f56d-4726-a381-d72376e83060");
            
            /// <summary> Asset Path (Sponza/16299174074766089871.jpg.wetx) </summary>
            public static readonly Guid _16299174074766089871_jpg = new Guid("07ff507b-daf9-4477-9b64-cfe1ee1d71e3");
            
            /// <summary> Asset Path (Sponza/12501374198249454378.jpg.wetx) </summary>
            public static readonly Guid _12501374198249454378_jpg = new Guid("67032435-3822-4677-a3e9-6ced7e80d499");
            
            /// <summary> Asset Path (Sponza/8747919177698443163.jpg.wetx) </summary>
            public static readonly Guid _8747919177698443163_jpg = new Guid("4be8e78d-d05b-49cc-9fe3-18377682f13a");
            
            /// <summary> Asset Path (Sponza/4601176305987539675.jpg.wetx) </summary>
            public static readonly Guid _4601176305987539675_jpg = new Guid("a73b5b50-783d-4f61-8607-b69a2a74d008");
            
            /// <summary> Asset Path (Sponza/14170708867020035030.jpg.wetx) </summary>
            public static readonly Guid _14170708867020035030_jpg = new Guid("e4d47f1f-7513-4cb7-a2e3-7b5399cac8e9");
            
            /// <summary> Asset Path (Sponza/8503262930880235456.jpg.wetx) </summary>
            public static readonly Guid _8503262930880235456_jpg = new Guid("33243e08-1240-410e-818c-f8fce8f7cbee");
            
            /// <summary> Asset Path (Sponza/2185409758123873465.jpg.wetx) </summary>
            public static readonly Guid _2185409758123873465_jpg = new Guid("c0f0e18a-e88d-409d-a31b-6f509fb9d4d7");
            
            /// <summary> Asset Path (Sponza/7815564343179553343.jpg.wetx) </summary>
            public static readonly Guid _7815564343179553343_jpg = new Guid("b82824c0-04fa-4c25-bad7-176ded065b6b");
            
            /// <summary> Asset Path (Sponza/14650633544276105767.jpg.wetx) </summary>
            public static readonly Guid _14650633544276105767_jpg = new Guid("0a86d643-4bd8-4c76-92ce-6d343abff041");
            
            /// <summary> Asset Path (Sponza/13196865903111448057.jpg.wetx) </summary>
            public static readonly Guid _13196865903111448057_jpg = new Guid("65c6741d-383e-4001-8a2c-a1b5c73e74db");
            
            /// <summary> Asset Path (Sponza/11490520546946913238.jpg.wetx) </summary>
            public static readonly Guid _11490520546946913238_jpg = new Guid("56ad40c3-dbd2-4c70-b3df-9589b708e109");
            
            /// <summary> Asset Path (Sponza/2374361008830720677.jpg.wetx) </summary>
            public static readonly Guid _2374361008830720677_jpg = new Guid("b1dd4e99-0560-457d-a756-a6b1c380c6bc");
            
            /// <summary> Asset Path (Sponza/466164707995436622.jpg.wetx) </summary>
            public static readonly Guid _466164707995436622_jpg = new Guid("09ef6ea9-8d12-4dd1-a4f2-856f38b825a3");
            
            /// <summary> Asset Path (Sponza/7056944414013900257.jpg.wetx) </summary>
            public static readonly Guid _7056944414013900257_jpg = new Guid("e700bd22-41c6-4dd1-b12c-5090edab8c23");
            
            /// <summary> Asset Path (Sponza/6151467286084645207.jpg.wetx) </summary>
            public static readonly Guid _6151467286084645207_jpg = new Guid("abff7f7d-6490-4d90-8c7d-9c67edda9c06");
            
            /// <summary> Asset Path (Sponza/755318871556304029.jpg.wetx) </summary>
            public static readonly Guid _755318871556304029_jpg = new Guid("ca7409f9-c8c2-4bde-b5c0-2a51b978ce36");
            
            /// <summary> Asset Path (Sponza/7645212358685992005.jpg.wetx) </summary>
            public static readonly Guid _7645212358685992005_jpg = new Guid("4607bf03-89e4-44fd-91f3-b750187470f9");
            
            /// <summary> Asset Path (Sponza/8051790464816141987.jpg.wetx) </summary>
            public static readonly Guid _8051790464816141987_jpg = new Guid("bc4652b9-e869-429b-ac71-87b83bf48678");
            
            /// <summary> Asset Path (Sponza/7441062115984513793.jpg.wetx) </summary>
            public static readonly Guid _7441062115984513793_jpg = new Guid("40c031e6-fc40-4149-964a-74b09ce6faed");
            
            /// <summary> Asset Path (Sponza/17876391417123941155.jpg.wetx) </summary>
            public static readonly Guid _17876391417123941155_jpg = new Guid("106df451-3867-4100-aa61-c9083ffe2378");
            
            /// <summary> Asset Path (Sponza/6772804448157695701.jpg.wetx) </summary>
            public static readonly Guid _6772804448157695701_jpg = new Guid("5e8ba4f5-9cec-40b9-ba3b-81f36c0de7e8");
            
            /// <summary> Asset Path (Sponza/3455394979645218238.jpg.wetx) </summary>
            public static readonly Guid _3455394979645218238_jpg = new Guid("412157ad-6c34-4736-9644-45da9ea40855");
            
            /// <summary> Asset Path (Sponza/10388182081421875623.jpg.wetx) </summary>
            public static readonly Guid _10388182081421875623_jpg = new Guid("ac76d7b1-0fb6-4a3f-8a07-863bb65c27bc");
            
            /// <summary> Asset Path (Sponza/13824894030729245199.jpg.wetx) </summary>
            public static readonly Guid _13824894030729245199_jpg = new Guid("d0ae1cd7-f7ff-4943-a01b-0bd3abd6ae5c");
            
            /// <summary> Asset Path (Sponza/332936164838540657.jpg.wetx) </summary>
            public static readonly Guid _332936164838540657_jpg = new Guid("99873747-b1f1-4bf4-bdc5-af3fbfb1761d");
            
            /// <summary> Asset Path (Sponza/15295713303328085182.jpg.wetx) </summary>
            public static readonly Guid _15295713303328085182_jpg = new Guid("0c7b0a81-1295-4289-8feb-4b544e50fa1a");
            
            /// <summary> Asset Path (Sponza/4477655471536070370.jpg.wetx) </summary>
            public static readonly Guid _4477655471536070370_jpg = new Guid("04b89241-afac-4c4d-a162-12c6833d9ff3");
            
            /// <summary> Asset Path (Sponza/4675343432951571524.jpg.wetx) </summary>
            public static readonly Guid _4675343432951571524_jpg = new Guid("76f7dac8-bc2a-4667-9690-dec31f88bb67");
            
            /// <summary> Asset Path (Sponza/2051777328469649772.jpg.wetx) </summary>
            public static readonly Guid _2051777328469649772_jpg = new Guid("da8c6a18-d90a-4bc8-86a3-ea0f8fc8fe56");
            
            public sealed class Sponza_Embedded
            {
                
                public sealed class Samplers
                {
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Samplers/Sampler0.wesp) </summary>
                    public static readonly Guid Sampler0 = new Guid("2a5ea5ed-321f-4b16-ab2a-eed370bc3af8");
                }
                
                public sealed class Materials
                {
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material0.wemt) </summary>
                    public static readonly Guid Material0 = new Guid("716138fe-57bb-4899-96cb-db6fcc924acb");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material24.wemt) </summary>
                    public static readonly Guid Material24 = new Guid("ab85460d-0f44-45e9-8716-44c390b68d01");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material4.wemt) </summary>
                    public static readonly Guid Material4 = new Guid("9adcca8e-9c13-46d4-bd8c-b0f10f2521db");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material18.wemt) </summary>
                    public static readonly Guid Material18 = new Guid("132fa036-6152-4c5e-850e-d65a997e6e7b");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material19.wemt) </summary>
                    public static readonly Guid Material19 = new Guid("ce247c2b-74bb-4461-9376-c23a9c5e0bb4");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material2.wemt) </summary>
                    public static readonly Guid Material2 = new Guid("89ac3f78-9c13-4a0a-97ee-f87976afc4d4");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material8.wemt) </summary>
                    public static readonly Guid Material8 = new Guid("0a947b0a-14fd-492e-9be3-dcf77e4dd0c8");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material10.wemt) </summary>
                    public static readonly Guid Material10 = new Guid("e1a532d6-be5a-47ec-8de5-390a81793111");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material6.wemt) </summary>
                    public static readonly Guid Material6 = new Guid("ea41fff7-9ad7-4d2c-9178-20a0903567eb");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material12.wemt) </summary>
                    public static readonly Guid Material12 = new Guid("181633d4-cacc-4336-936d-52fbf41556ac");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material11.wemt) </summary>
                    public static readonly Guid Material11 = new Guid("3633a59a-9508-45ee-ba4a-b25ba2abdf4f");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material13.wemt) </summary>
                    public static readonly Guid Material13 = new Guid("e1398142-8de7-44be-b9a9-eec1c9369166");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material9.wemt) </summary>
                    public static readonly Guid Material9 = new Guid("c7f0f074-564e-4cc4-b6df-69caeb06793f");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material14.wemt) </summary>
                    public static readonly Guid Material14 = new Guid("adab7741-7b8d-43a4-a0ff-e7a802dafd43");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material3.wemt) </summary>
                    public static readonly Guid Material3 = new Guid("8adb65dc-3e2c-4b62-b91c-42596ae12e3b");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material16.wemt) </summary>
                    public static readonly Guid Material16 = new Guid("d5e8f286-f945-423d-a7b4-d6e51a88bf24");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material15.wemt) </summary>
                    public static readonly Guid Material15 = new Guid("05cfe699-8632-4f79-a68a-83849c0c255a");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material1.wemt) </summary>
                    public static readonly Guid Material1 = new Guid("92c37ebe-9cae-46ff-add4-dda82ff3645f");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material17.wemt) </summary>
                    public static readonly Guid Material17 = new Guid("5df89f77-f89a-4c27-a564-1bb49030ca85");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material7.wemt) </summary>
                    public static readonly Guid Material7 = new Guid("90acd54a-19d6-415b-8ce3-385b690f5b16");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material20.wemt) </summary>
                    public static readonly Guid Material20 = new Guid("62dddf81-6b1a-4121-9154-ecd724eefa28");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material5.wemt) </summary>
                    public static readonly Guid Material5 = new Guid("7cd97642-b9c9-4758-8248-07f83c64aeee");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material22.wemt) </summary>
                    public static readonly Guid Material22 = new Guid("f9b0306a-dcf1-442b-8b77-373e2f889c1e");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material21.wemt) </summary>
                    public static readonly Guid Material21 = new Guid("93d32730-fd71-4712-93d8-2bc5244e3b73");
                    
                    /// <summary> Asset Path (Sponza/Sponza_Embedded/Materials/Material23.wemt) </summary>
                    public static readonly Guid Material23 = new Guid("9e0ecd4b-980d-41ef-8bef-828d62c5730f");
                }
            }
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary> Asset Path (RenderLayers/Alpha.werl) </summary>
            public static readonly Guid Alpha = new Guid("e35c59a9-26ab-4b4c-8210-4b1f21c31530");
            
            /// <summary> Asset Path (RenderLayers/Opaque.werl) </summary>
            public static readonly Guid Opaque = new Guid("0db59561-b3f5-444f-b5de-e62e3a5b42bf");
        }
    }
}
